### ISSUE TITLE
Target variables at specific fxos-components

### ISSUE THREAD

**Issue by wilsonpage** [fxos-components/gaia-theme#11]

**Comment by wilsonpage** [comment]
To avoid super specific variable names we can just scope generic names to web components:

```css
.theme-settings gaia-header {
  --fxos-action-button-color: ...,
  --fxos-button-color: ...,
  --fxos-icon-color: ...,
}
```
